"""add_contrato_honorario

Revision ID: 0c239a615f4e
Revises: 872cf27b6dcd
Create Date: 2026-04-08 16:13:54.365606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c239a615f4e'
down_revision = '872cf27b6dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato_honorario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_honorario', sa.String(length=50), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('percentual_exito', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('data_assinatura', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('notas_condicoes', sa.Text(), nullable=True),
    sa.Column('caso_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['caso.id'], name='fk_contrato_caso_id'),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='fk_contrato_cliente_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_contrato_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recebimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrato_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_recebimento_contrato_id', 'contrato_honorario', ['contrato_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recebimento', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recebimento_contrato_id', type_='foreignkey')
        batch_op.drop_column('contrato_id')

    op.drop_table('contrato_honorario')
    # ### end Alembic commands ###
