"""expand_evento_agenda_for_alerts

Revision ID: 15dcb0ed3871
Revises: 0c239a615f4e
Create Date: 2026-04-08 16:22:09.257601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15dcb0ed3871'
down_revision = '0c239a615f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_agenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_evento', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('prioridade', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('status_evento', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('notificacoes_enviadas', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_agenda', schema=None) as batch_op:
        batch_op.drop_column('notificacoes_enviadas')
        batch_op.drop_column('status_evento')
        batch_op.drop_column('prioridade')
        batch_op.drop_column('tipo_evento')

    # ### end Alembic commands ###
