"""add tenant contact fields

Revision ID: 285cafac29e0
Revises: 80366d78be69
Create Date: 2026-04-22 09:56:33.491596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285cafac29e0'
down_revision = '80366d78be69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_tentativa', sa.String(length=120), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('motivo_falha', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_login_audit_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_audit_criado_em'), ['criado_em'], unique=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_tenant_created', ['tenant_id', 'data_hora'], unique=False)

    with op.batch_alter_table('despesa', schema=None) as batch_op:
        batch_op.create_index('ix_despesa_tenant_created', ['tenant_id', 'data_despesa'], unique=False)

    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.create_index('ix_documento_tenant_created', ['tenant_id', 'data_upload'], unique=False)

    with op.batch_alter_table('evento_agenda', schema=None) as batch_op:
        batch_op.create_index('ix_evento_agenda_tenant_created', ['tenant_id', 'data_inicio'], unique=False)

    with op.batch_alter_table('movimentacao_cnj', schema=None) as batch_op:
        batch_op.create_index('ix_movimentacao_cnj_tenant_created', ['caso_id', 'data_registro_sistema'], unique=False)

    with op.batch_alter_table('publicacao_djen', schema=None) as batch_op:
        batch_op.create_index('ix_publicacao_djen_tenant_created', ['tenant_id', 'data_captura'], unique=False)

    with op.batch_alter_table('recebimento', schema=None) as batch_op:
        batch_op.create_index('ix_recebimento_tenant_created', ['tenant_id', 'data_recebimento'], unique=False)

    with op.batch_alter_table('tarefa_prazo', schema=None) as batch_op:
        batch_op.create_index('ix_tarefa_prazo_tenant_created', ['tenant_id', 'data_criacao'], unique=False)

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_contato', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('numero_oab_escritorio', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('sigla_oab_escritorio', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('endereco')
        batch_op.drop_column('sigla_oab_escritorio')
        batch_op.drop_column('numero_oab_escritorio')
        batch_op.drop_column('telefone')
        batch_op.drop_column('email_contato')

    with op.batch_alter_table('tarefa_prazo', schema=None) as batch_op:
        batch_op.drop_index('ix_tarefa_prazo_tenant_created')

    with op.batch_alter_table('recebimento', schema=None) as batch_op:
        batch_op.drop_index('ix_recebimento_tenant_created')

    with op.batch_alter_table('publicacao_djen', schema=None) as batch_op:
        batch_op.drop_index('ix_publicacao_djen_tenant_created')

    with op.batch_alter_table('movimentacao_cnj', schema=None) as batch_op:
        batch_op.drop_index('ix_movimentacao_cnj_tenant_created')

    with op.batch_alter_table('evento_agenda', schema=None) as batch_op:
        batch_op.drop_index('ix_evento_agenda_tenant_created')

    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_index('ix_documento_tenant_created')

    with op.batch_alter_table('despesa', schema=None) as batch_op:
        batch_op.drop_index('ix_despesa_tenant_created')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_tenant_created')

    with op.batch_alter_table('login_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_audit_criado_em'))

    op.drop_table('login_audit')
    # ### end Alembic commands ###
