"""add_audit_log_table

Revision ID: 298460f53959
Revises: 5b79e49ac698
Create Date: 2026-04-09 09:30:51.123079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298460f53959'
down_revision = '5b79e49ac698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('tabela_afetada', sa.String(length=50), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name='fk_auditlog_tenant_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_auditlog_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_data_hora'), ['data_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_data_hora'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
