"""Add TarefaPrazo

Revision ID: 2c0abaea2600
Revises: 298460f53959
Create Date: 2026-04-09 15:20:55.977225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0abaea2600'
down_revision = '298460f53959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefa_prazo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=250), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('prioridade', sa.String(length=50), nullable=True),
    sa.Column('data_vencimento', sa.DateTime(), nullable=True),
    sa.Column('tipo_tarefa', sa.String(length=50), nullable=True),
    sa.Column('origem_id', sa.String(length=100), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caso_id'], ['caso.id'], name='fk_tarefaprazo_caso_id'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name='fk_tarefaprazo_tenant_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_tarefaprazo_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarefa_prazo')
    # ### end Alembic commands ###
