"""sync_publicacao_djen_schema

Revision ID: 2f86e47cd662
Revises: f40f4936568d
Create Date: 2026-04-16 14:17:05.694920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '2f86e47cd662'
down_revision = 'f40f4936568d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('djen_oab_monitoramento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('numero_oab', sa.String(length=30), nullable=False),
    sa.Column('uf_oab', sa.String(length=2), nullable=True),
    sa.Column('nome_advogado', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('ultima_sincronizacao', sa.DateTime(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name='fk_djen_oab_tenant_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_djen_oab_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'numero_oab', 'uf_oab', name='uq_djen_oab_tenant')
    )
    op.create_table('publicacao_djen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=True),
    sa.Column('djen_id', sa.BigInteger(), nullable=True),
    sa.Column('hash_comunicacao', sa.String(length=100), nullable=True),
    sa.Column('numero_comunicacao', sa.Integer(), nullable=True),
    sa.Column('numero_processo', sa.String(length=50), nullable=True),
    sa.Column('numero_processo_mascara', sa.String(length=50), nullable=True),
    sa.Column('sigla_tribunal', sa.String(length=20), nullable=True),
    sa.Column('nome_orgao', sa.String(length=200), nullable=True),
    sa.Column('tipo_comunicacao', sa.String(length=100), nullable=True),
    sa.Column('tipo_documento', sa.String(length=100), nullable=True),
    sa.Column('nome_classe', sa.String(length=200), nullable=True),
    sa.Column('data_disponibilizacao', sa.Date(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('meio', sa.String(length=1), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('origem_busca', sa.String(length=20), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('data_captura', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caso_id'], ['caso.id'], name='fk_pub_djen_caso_id'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name='fk_pub_djen_tenant_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_pub_djen_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'djen_id', name='uq_pub_djen_tenant_djenid')
    )
    with op.batch_alter_table('publicacao_djen', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publicacao_djen_data_disponibilizacao'), ['data_disponibilizacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_publicacao_djen_djen_id'), ['djen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publicacao_djen_hash_comunicacao'), ['hash_comunicacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_publicacao_djen_lida'), ['lida'], unique=False)
        batch_op.create_index(batch_op.f('ix_publicacao_djen_numero_processo'), ['numero_processo'], unique=False)
        batch_op.create_index(batch_op.f('ix_publicacao_djen_sigla_tribunal'), ['sigla_tribunal'], unique=False)

    with op.batch_alter_table('djen_publicacao', schema=None) as batch_op:
        batch_op.drop_index('ix_djen_publicacao_hash')
        batch_op.drop_index('ix_djen_publicacao_numero_processo')

    op.drop_table('djen_publicacao')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('djen_publicacao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=True),
    sa.Column('caso_id', sa.INTEGER(), nullable=True),
    sa.Column('hash_comunicacao', sa.VARCHAR(length=100), nullable=True),
    sa.Column('numero_processo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sigla_tribunal', sa.VARCHAR(length=20), nullable=True),
    sa.Column('tipo_comunicacao', sa.VARCHAR(length=200), nullable=True),
    sa.Column('data_disponibilizacao', sa.DATETIME(), nullable=True),
    sa.Column('data_disponibilizacao_str', sa.VARCHAR(length=50), nullable=True),
    sa.Column('texto', sa.TEXT(), nullable=True),
    sa.Column('nome_parte', sa.VARCHAR(length=300), nullable=True),
    sa.Column('meio', sa.VARCHAR(length=1), nullable=True),
    sa.Column('dados_raw', sqlite.JSON(), nullable=True),
    sa.Column('lida', sa.BOOLEAN(), nullable=True),
    sa.Column('origem_busca', sa.VARCHAR(length=20), nullable=True),
    sa.Column('data_captura', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['caso_id'], ['caso.id'], name='fk_djen_pub_caso_id'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name='fk_djen_pub_tenant_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_djen_pub_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('djen_publicacao', schema=None) as batch_op:
        batch_op.create_index('ix_djen_publicacao_numero_processo', ['numero_processo'], unique=False)
        batch_op.create_index('ix_djen_publicacao_hash', ['hash_comunicacao'], unique=False)

    with op.batch_alter_table('publicacao_djen', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publicacao_djen_sigla_tribunal'))
        batch_op.drop_index(batch_op.f('ix_publicacao_djen_numero_processo'))
        batch_op.drop_index(batch_op.f('ix_publicacao_djen_lida'))
        batch_op.drop_index(batch_op.f('ix_publicacao_djen_hash_comunicacao'))
        batch_op.drop_index(batch_op.f('ix_publicacao_djen_djen_id'))
        batch_op.drop_index(batch_op.f('ix_publicacao_djen_data_disponibilizacao'))

    op.drop_table('publicacao_djen')
    op.drop_table('djen_oab_monitoramento')
    # ### end Alembic commands ###
