"""add portal_cliente_id to user

Revision ID: 44d93d733c33
Revises: 285cafac29e0
Create Date: 2026-04-22 10:46:09.156502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d93d733c33'
down_revision = '285cafac29e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portal_cliente_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_portal_cliente_id', 'cliente', ['portal_cliente_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_portal_cliente_id', type_='foreignkey')
        batch_op.drop_column('portal_cliente_id')

    # ### end Alembic commands ###
