"""add_tenant_module

Revision ID: 5b79e49ac698
Revises: 15dcb0ed3871
Create Date: 2026-04-08 18:07:22.893350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b79e49ac698'
down_revision = '15dcb0ed3871'
branch_labels = None
depends_on = None


def _table_exists(table_name):
    """Verifica se uma tabela já existe no SQLite."""
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT name FROM sqlite_master WHERE type='table' AND name=:name"
    ), {"name": table_name})
    return result.fetchone() is not None

def _column_exists(table_name, column_name):
    """Verifica se uma coluna já existe em uma tabela no SQLite."""
    conn = op.get_bind()
    result = conn.execute(sa.text(f"PRAGMA table_info({table_name})"))
    columns = [row[1] for row in result.fetchall()]
    return column_name in columns

def _add_tenant_id_if_missing(table_name, fk_name):
    """Adiciona tenant_id a uma tabela somente se a coluna não existir."""
    if not _column_exists(table_name, 'tenant_id'):
        with op.batch_alter_table(table_name, schema=None) as batch_op:
            batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(fk_name, 'tenant', ['tenant_id'], ['id'])

def upgrade():
    # Limpar tabela temporária residual de migração falha anterior
    if _table_exists('_alembic_tmp_caso'):
        op.drop_table('_alembic_tmp_caso')

    # Criar tabela tenant somente se não existir
    if not _table_exists('tenant'):
        op.create_table('tenant',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('nome_escritorio', sa.String(length=250), nullable=False),
            sa.Column('documento', sa.String(length=20), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )

    # Adicionar tenant_id em cada tabela (verificando antes se já existe)
    _add_tenant_id_if_missing('caso', 'fk_caso_tenant_id')
    _add_tenant_id_if_missing('cliente', 'fk_cliente_tenant_id')
    _add_tenant_id_if_missing('contrato_honorario', 'fk_contrato_tenant_id')
    _add_tenant_id_if_missing('despesa', 'fk_despesa_tenant_id')
    _add_tenant_id_if_missing('documento', 'fk_documento_tenant_id')
    _add_tenant_id_if_missing('evento_agenda', 'fk_evento_tenant_id')
    _add_tenant_id_if_missing('recebimento', 'fk_recebimento_tenant_id')
    _add_tenant_id_if_missing('user', 'fk_user_tenant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('recebimento', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recebimento_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('evento_agenda', schema=None) as batch_op:
        batch_op.drop_constraint('fk_evento_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documento_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('despesa', schema=None) as batch_op:
        batch_op.drop_constraint('fk_despesa_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('contrato_honorario', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contrato_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cliente_tenant_id', type_='foreignkey')
        batch_op.create_unique_constraint('cliente_email_key', ['email'])
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.drop_constraint('fk_caso_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    op.drop_table('tenant')
    # ### end Alembic commands ###
