"""add_tenant_module

Revision ID: 5b79e49ac698
Revises: 15dcb0ed3871
Create Date: 2026-04-08 18:07:22.893350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b79e49ac698'
down_revision = '15dcb0ed3871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_escritorio', sa.String(length=250), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_caso_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('cliente_email_key', type_='unique')
        batch_op.create_foreign_key('fk_cliente_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('contrato_honorario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_contrato_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('despesa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_despesa_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_documento_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('evento_agenda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_evento_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('recebimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_recebimento_tenant_id', 'tenant', ['tenant_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_tenant_id', 'tenant', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('recebimento', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recebimento_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('evento_agenda', schema=None) as batch_op:
        batch_op.drop_constraint('fk_evento_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('documento', schema=None) as batch_op:
        batch_op.drop_constraint('fk_documento_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('despesa', schema=None) as batch_op:
        batch_op.drop_constraint('fk_despesa_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('contrato_honorario', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contrato_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cliente_tenant_id', type_='foreignkey')
        batch_op.create_unique_constraint('cliente_email_key', ['email'])
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.drop_constraint('fk_caso_tenant_id', type_='foreignkey')
        batch_op.drop_column('tenant_id')

    op.drop_table('tenant')
    # ### end Alembic commands ###
