"""expand_caso_model

Revision ID: 718a903bd3bc
Revises: 82e22d622b8c
Create Date: 2026-04-08 15:53:17.198951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718a903bd3bc'
down_revision = '82e22d622b8c'
branch_labels = None
depends_on = None


def upgrade():
    # Passo 1: Adicionar titulo como nullable para preservar dados existentes
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tipo_acao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('area_direito', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('fase_processual', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('vara_juizo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('comarca', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('instancia', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('parte_contraria', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('adv_parte_contraria', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('valor_causa', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('data_distribuicao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('notas_caso', sa.Text(), nullable=True))

    # Passo 2: Copiar dados existentes
    op.execute("UPDATE caso SET titulo = nome_caso WHERE titulo IS NULL")
    op.execute("UPDATE caso SET notas_caso = descricao WHERE notas_caso IS NULL AND descricao IS NOT NULL")

    # Passo 3: Tornar titulo NOT NULL e remover colunas antigas
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.alter_column('titulo', nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('nome_caso')
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('nome_caso', sa.VARCHAR(length=150), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('notas_caso')
        batch_op.drop_column('data_distribuicao')
        batch_op.drop_column('valor_causa')
        batch_op.drop_column('adv_parte_contraria')
        batch_op.drop_column('parte_contraria')
        batch_op.drop_column('instancia')
        batch_op.drop_column('comarca')
        batch_op.drop_column('vara_juizo')
        batch_op.drop_column('fase_processual')
        batch_op.drop_column('area_direito')
        batch_op.drop_column('tipo_acao')
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
