"""expand_cliente_model_25_fields

Revision ID: 82e22d622b8c
Revises: f11cc3232943
Create Date: 2026-04-08 15:26:28.651689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e22d622b8c'
down_revision = 'f11cc3232943'
branch_labels = None
depends_on = None


def upgrade():
    # Passo 1: Adicionar novas colunas como nullable para compatibilidade com dados existentes
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_razao_social', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cpf_cnpj', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tipo_pessoa', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('rg', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('orgao_emissor', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('estado_civil', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('profissao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nacionalidade', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('nome_fantasia', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('nire', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('inscricao_estadual', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('inscricao_municipal', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('cnpj_secundario', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('descricao_cnpj_secundario', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cnpj_terciario', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('descricao_cnpj_terciario', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('rua', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('pais', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('notas_gerais', sa.Text(), nullable=True))

    # Passo 2: Copiar dados existentes da coluna 'nome' para 'nome_razao_social'
    op.execute("UPDATE cliente SET nome_razao_social = nome WHERE nome_razao_social IS NULL")
    op.execute("UPDATE cliente SET cpf_cnpj = '00000000000' WHERE cpf_cnpj IS NULL")
    op.execute("UPDATE cliente SET tipo_pessoa = 'PF' WHERE tipo_pessoa IS NULL")

    # Passo 3: Remover coluna antiga e tornar campos NOT NULL (SQLite precisa de batch)
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('nome_razao_social', nullable=False)
        batch_op.alter_column('cpf_cnpj', nullable=False)
        batch_op.alter_column('tipo_pessoa', nullable=False)
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('notas_gerais')
        batch_op.drop_column('pais')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('numero')
        batch_op.drop_column('rua')
        batch_op.drop_column('cep')
        batch_op.drop_column('descricao_cnpj_terciario')
        batch_op.drop_column('cnpj_terciario')
        batch_op.drop_column('descricao_cnpj_secundario')
        batch_op.drop_column('cnpj_secundario')
        batch_op.drop_column('inscricao_municipal')
        batch_op.drop_column('inscricao_estadual')
        batch_op.drop_column('nire')
        batch_op.drop_column('nome_fantasia')
        batch_op.drop_column('nacionalidade')
        batch_op.drop_column('profissao')
        batch_op.drop_column('estado_civil')
        batch_op.drop_column('data_nascimento')
        batch_op.drop_column('orgao_emissor')
        batch_op.drop_column('rg')
        batch_op.drop_column('tipo_pessoa')
        batch_op.drop_column('cpf_cnpj')
        batch_op.drop_column('nome_razao_social')

    # ### end Alembic commands ###
