"""add_role_to_user

Revision ID: 872cf27b6dcd
Revises: 718a903bd3bc
Create Date: 2026-04-08 16:02:31.349164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872cf27b6dcd'
down_revision = '718a903bd3bc'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
    
    op.execute("UPDATE \"user\" SET role = 'admin' WHERE role IS NULL")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
