"""add_descricao_to_caso

Revision ID: 95fd9fcb32b4
Revises: e3f4a5b6c7d8
Create Date: 2026-05-01 14:29:24.577011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95fd9fcb32b4'
down_revision = 'e3f4a5b6c7d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.Text(), nullable=True))

    with op.batch_alter_table('djen_sync_job', schema=None) as batch_op:
        batch_op.drop_index('ix_djen_sync_job_status_criado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('djen_sync_job', schema=None) as batch_op:
        batch_op.create_index('ix_djen_sync_job_status_criado', ['status', 'criado_em'], unique=False)

    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
