"""Initial migration

Revision ID: f11cc3232943
Revises: 
Create Date: 2026-03-06 11:18:16.255891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11cc3232943'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_cliente_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('evento_agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_evento_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_caso', sa.String(length=150), nullable=False),
    sa.Column('numero_processo', sa.String(length=30), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_ultima_verificacao_cnj', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name='fk_caso_cliente_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_caso_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caso_numero_processo'), ['numero_processo'], unique=False)

    op.create_table('despesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_despesa', sa.Date(), nullable=False),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.Column('caso_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['caso.id'], name='fk_despesa_caso_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_despesa_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('path_arquivo', sa.String(length=500), nullable=False),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.Column('caso_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['caso.id'], name='fk_documento_caso_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_documento_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacao_cnj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('dados_integra_cnj', sa.JSON(), nullable=True),
    sa.Column('data_registro_sistema', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caso_id'], ['caso.id'], name='fk_movimentacao_cnj_caso_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimentacao_cnj', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentacao_cnj_caso_id'), ['caso_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacao_cnj_data_movimentacao'), ['data_movimentacao'], unique=False)

    op.create_table('recebimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_recebimento', sa.Date(), nullable=False),
    sa.Column('recebido', sa.Boolean(), nullable=True),
    sa.Column('caso_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['caso.id'], name='fk_recebimento_caso_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_recebimento_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recebimento')
    with op.batch_alter_table('movimentacao_cnj', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentacao_cnj_data_movimentacao'))
        batch_op.drop_index(batch_op.f('ix_movimentacao_cnj_caso_id'))

    op.drop_table('movimentacao_cnj')
    op.drop_table('documento')
    op.drop_table('despesa')
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caso_numero_processo'))

    op.drop_table('caso')
    op.drop_table('evento_agenda')
    op.drop_table('cliente')
    op.drop_table('user')
    # ### end Alembic commands ###
