from .auth import register_auth_routes
from .auditoria import register_auditoria_routes
from .casos import register_casos_routes
from .clientes import register_clientes_routes
from .contratos import register_contratos_routes
from .dashboard import register_dashboard_routes
from .despesas import register_despesas_routes
from .documentos import register_documentos_routes
from .eventos import register_eventos_routes
from .recebimentos import register_recebimentos_routes
from .tarefas import register_tarefas_routes
