// Issue #300 (parte 3) — extraído de DjenPage.jsx.
// ── Lista completa de tribunais brasileiros ────────────────────────────────
export const TRIBUNAIS = [
  // Superiores
  { sigla: 'STF', nome: 'Supremo Tribunal Federal' },
  { sigla: 'STJ', nome: 'Superior Tribunal de Justiça' },
  { sigla: 'TST', nome: 'Tribunal Superior do Trabalho' },
  { sigla: 'TSE', nome: 'Tribunal Superior Eleitoral' },
  { sigla: 'STM', nome: 'Superior Tribunal Militar' },
  // TRFs
  { sigla: 'TRF1', nome: 'TRF 1ª Região (DF, MG, GO, BA…)' },
  { sigla: 'TRF2', nome: 'TRF 2ª Região (RJ, ES)' },
  { sigla: 'TRF3', nome: 'TRF 3ª Região (SP, MS)' },
  { sigla: 'TRF4', nome: 'TRF 4ª Região (RS, SC, PR)' },
  { sigla: 'TRF5', nome: 'TRF 5ª Região (CE, RN, PB, PE, AL, SE)' },
  { sigla: 'TRF6', nome: 'TRF 6ª Região (MG)' },
  // TJs
  { sigla: 'TJAC', nome: 'TJAC – Acre' },
  { sigla: 'TJAL', nome: 'TJAL – Alagoas' },
  { sigla: 'TJAM', nome: 'TJAM – Amazonas' },
  { sigla: 'TJAP', nome: 'TJAP – Amapá' },
  { sigla: 'TJBA', nome: 'TJBA – Bahia' },
  { sigla: 'TJCE', nome: 'TJCE – Ceará' },
  { sigla: 'TJDFT', nome: 'TJDFT – Distrito Federal' },
  { sigla: 'TJES', nome: 'TJES – Espírito Santo' },
  { sigla: 'TJGO', nome: 'TJGO – Goiás' },
  { sigla: 'TJMA', nome: 'TJMA – Maranhão' },
  { sigla: 'TJMG', nome: 'TJMG – Minas Gerais' },
  { sigla: 'TJMS', nome: 'TJMS – Mato Grosso do Sul' },
  { sigla: 'TJMT', nome: 'TJMT – Mato Grosso' },
  { sigla: 'TJPA', nome: 'TJPA – Pará' },
  { sigla: 'TJPB', nome: 'TJPB – Paraíba' },
  { sigla: 'TJPE', nome: 'TJPE – Pernambuco' },
  { sigla: 'TJPI', nome: 'TJPI – Piauí' },
  { sigla: 'TJPR', nome: 'TJPR – Paraná' },
  { sigla: 'TJRJ', nome: 'TJRJ – Rio de Janeiro' },
  { sigla: 'TJRN', nome: 'TJRN – Rio Grande do Norte' },
  { sigla: 'TJRO', nome: 'TJRO – Rondônia' },
  { sigla: 'TJRR', nome: 'TJRR – Roraima' },
  { sigla: 'TJRS', nome: 'TJRS – Rio Grande do Sul' },
  { sigla: 'TJSC', nome: 'TJSC – Santa Catarina' },
  { sigla: 'TJSE', nome: 'TJSE – Sergipe' },
  { sigla: 'TJSP', nome: 'TJSP – São Paulo' },
  { sigla: 'TJTO', nome: 'TJTO – Tocantins' },
  // TRTs
  { sigla: 'TRT1', nome: 'TRT 1ª Região (RJ)' },
  { sigla: 'TRT2', nome: 'TRT 2ª Região (SP Capital)' },
  { sigla: 'TRT3', nome: 'TRT 3ª Região (MG)' },
  { sigla: 'TRT4', nome: 'TRT 4ª Região (RS)' },
  { sigla: 'TRT5', nome: 'TRT 5ª Região (BA)' },
  { sigla: 'TRT6', nome: 'TRT 6ª Região (PE)' },
  { sigla: 'TRT7', nome: 'TRT 7ª Região (CE)' },
  { sigla: 'TRT8', nome: 'TRT 8ª Região (PA e AP)' },
  { sigla: 'TRT9', nome: 'TRT 9ª Região (PR)' },
  { sigla: 'TRT10', nome: 'TRT 10ª Região (DF e TO)' },
  { sigla: 'TRT11', nome: 'TRT 11ª Região (AM e RR)' },
  { sigla: 'TRT12', nome: 'TRT 12ª Região (SC)' },
  { sigla: 'TRT13', nome: 'TRT 13ª Região (PB)' },
  { sigla: 'TRT14', nome: 'TRT 14ª Região (RO e AC)' },
  { sigla: 'TRT15', nome: 'TRT 15ª Região (SP Interior)' },
  { sigla: 'TRT16', nome: 'TRT 16ª Região (MA)' },
  { sigla: 'TRT17', nome: 'TRT 17ª Região (ES)' },
  { sigla: 'TRT18', nome: 'TRT 18ª Região (GO)' },
  { sigla: 'TRT19', nome: 'TRT 19ª Região (AL)' },
  { sigla: 'TRT20', nome: 'TRT 20ª Região (SE)' },
  { sigla: 'TRT21', nome: 'TRT 21ª Região (RN)' },
  { sigla: 'TRT22', nome: 'TRT 22ª Região (PI)' },
  { sigla: 'TRT23', nome: 'TRT 23ª Região (MT)' },
  { sigla: 'TRT24', nome: 'TRT 24ª Região (MS)' },
  // TREs
  { sigla: 'TREAC', nome: 'TRE – Acre' },
  { sigla: 'TREAL', nome: 'TRE – Alagoas' },
  { sigla: 'TREAM', nome: 'TRE – Amazonas' },
  { sigla: 'TREAP', nome: 'TRE – Amapá' },
  { sigla: 'TREBA', nome: 'TRE – Bahia' },
  { sigla: 'TRECE', nome: 'TRE – Ceará' },
  { sigla: 'TREDF', nome: 'TRE – Distrito Federal' },
  { sigla: 'TREES', nome: 'TRE – Espírito Santo' },
  { sigla: 'TREGO', nome: 'TRE – Goiás' },
  { sigla: 'TREMA', nome: 'TRE – Maranhão' },
  { sigla: 'TREMG', nome: 'TRE – Minas Gerais' },
  { sigla: 'TREMS', nome: 'TRE – Mato Grosso do Sul' },
  { sigla: 'TREMT', nome: 'TRE – Mato Grosso' },
  { sigla: 'TREPA', nome: 'TRE – Pará' },
  { sigla: 'TREPB', nome: 'TRE – Paraíba' },
  { sigla: 'TREPE', nome: 'TRE – Pernambuco' },
  { sigla: 'TREPI', nome: 'TRE – Piauí' },
  { sigla: 'TREPR', nome: 'TRE – Paraná' },
  { sigla: 'TRERJ', nome: 'TRE – Rio de Janeiro' },
  { sigla: 'TRERN', nome: 'TRE – Rio Grande do Norte' },
  { sigla: 'TRERO', nome: 'TRE – Rondônia' },
  { sigla: 'TRERR', nome: 'TRE – Roraima' },
  { sigla: 'TRERS', nome: 'TRE – Rio Grande do Sul' },
  { sigla: 'TRESC', nome: 'TRE – Santa Catarina' },
  { sigla: 'TRESE', nome: 'TRE – Sergipe' },
  { sigla: 'TRESP', nome: 'TRE – São Paulo' },
  { sigla: 'TRETO', nome: 'TRE – Tocantins' },
  // TJMs
  { sigla: 'TJMMG', nome: 'TJM – Minas Gerais' },
  { sigla: 'TJMRS', nome: 'TJM – Rio Grande do Sul' },
  { sigla: 'TJMSP', nome: 'TJM – São Paulo' },
]
