# Generated by Django 5.2.1 on 2025-05-21 12:33

import django.db.models.deletion
import django.utils.timezone
import gestao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao_social', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('orgao_emissor', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='Brasileiro(a)', max_length=100, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('nire', models.CharField(blank=True, max_length=50, null=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=50, null=True)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('pais', models.CharField(blank=True, default='Brasil', max_length=50, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('notas_gerais', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('numero_processo', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Suspenso', 'Suspenso'), ('Encerrado', 'Encerrado'), ('Arquivado', 'Arquivado')], default='Ativo', max_length=50)),
                ('parte_contraria', models.CharField(blank=True, max_length=255, null=True)),
                ('adv_parte_contraria', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_acao', models.CharField(blank=True, max_length=100, null=True)),
                ('vara_juizo', models.CharField(blank=True, max_length=100, null=True)),
                ('comarca', models.CharField(blank=True, max_length=100, null=True)),
                ('instancia', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_causa', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('data_distribuicao', models.DateField(blank=True, null=True)),
                ('notas_caso', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='gestao.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_despesa', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Custas Processuais', 'Custas Processuais'), ('Honorários Periciais', 'Honorários Periciais'), ('Cópias e Impressões', 'Cópias e Impressões'), ('Deslocamento/Viagem', 'Deslocamento/Viagem'), ('Aluguel Escritório', 'Aluguel Escritório'), ('Contas (Água, Luz, Internet, Telefone)', 'Contas (Água, Luz, Internet, Telefone)'), ('Software e Assinaturas', 'Software e Assinaturas'), ('Material de Escritório', 'Material de Escritório'), ('Marketing e Publicidade', 'Marketing e Publicidade'), ('Impostos e Taxas Escritório', 'Impostos e Taxas Escritório'), ('Outras Despesas', 'Outras Despesas')], default='Custas Processuais', max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('A Pagar', 'A Pagar'), ('Paga', 'Paga'), ('Vencida', 'Vencida'), ('Cancelada', 'Cancelada')], default='A Pagar', max_length=50)),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='gestao.caso')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=gestao.models.get_upload_path)),
                ('nome_original_arquivo', models.CharField(blank=True, max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_caso', to='gestao.caso')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_cliente', to='gestao.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('Prazo', 'Prazo'), ('Audiência', 'Audiência'), ('Reunião', 'Reunião'), ('Lembrete', 'Lembrete'), ('Outro', 'Outro')], default='Lembrete', max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='gestao.caso')),
            ],
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Honorários Advocatícios', 'Honorários Advocatícios'), ('Honorários de Êxito', 'Honorários de Êxito'), ('Consultoria', 'Consultoria'), ('Custas Processuais (Reembolso)', 'Custas Processuais (Reembolso)'), ('Despesas (Reembolso)', 'Despesas (Reembolso)'), ('Acordo Judicial', 'Acordo Judicial'), ('Outros Recebimentos', 'Outros Recebimentos')], default='Honorários Advocatícios', max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Vencido', 'Vencido'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=50)),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='gestao.caso')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos_cliente', to='gestao.cliente')),
            ],
        ),
    ]
