# Generated by Django 5.2.1 on 2025-05-21 14:41

import django.db.models.deletion
import django.utils.timezone
import gestao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='nome_armazenado',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='Nome Armazenado no Servidor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tamanho_bytes',
            field=models.BigIntegerField(blank=True, editable=False, null=True, verbose_name='Tamanho (bytes)'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_mime',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='Tipo MIME'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='adv_parte_contraria',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Advogado da Parte Contrária'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='gestao.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='comarca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comarca'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='data_distribuicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Distribuição/Início'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='instancia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instância'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='notas_caso',
            field=models.TextField(blank=True, null=True, verbose_name='Notas sobre o Caso'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Número do Processo'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='parte_contraria',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Parte Contrária'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Pendente', 'Pendente'), ('Suspenso', 'Suspenso'), ('Encerrado', 'Encerrado'), ('Arquivado', 'Arquivado')], default='Ativo', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='tipo_acao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Ação/Natureza'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título do Caso'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='valor_causa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor da Causa'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='vara_juizo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vara/Juízo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, choices=[('', '---------'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('União Estável', 'União Estável')], max_length=50, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nacionalidade',
            field=models.CharField(blank=True, default='Brasileiro(a)', max_length=100, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nire',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NIRE'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_razao_social',
            field=models.CharField(max_length=255, verbose_name='Nome / Razão Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='notas_gerais',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Gerais'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='orgao_emissor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Órgão Emissor'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='pais',
            field=models.CharField(blank=True, default='Brasil', max_length=50, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua/Logradouro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, verbose_name='Tipo de Pessoa'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='caso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_caso', to='gestao.caso', verbose_name='Caso Associado (Opcional)'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('Custas Judiciais', 'Custas Judiciais'), ('Cópias e Impressões', 'Cópias e Impressões'), ('Deslocamento', 'Deslocamento'), ('Serviços de Terceiros', 'Serviços de Terceiros (Peritos, etc.)'), ('Correspondente Jurídico', 'Correspondente Jurídico'), ('Despesas Administrativas', 'Despesas Administrativas (Escritório)'), ('Outras', 'Outras')], max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_despesa',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Despesa/Pagamento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('A Pagar', 'A Pagar'), ('Paga', 'Paga'), ('Vencida', 'Vencida'), ('Cancelada', 'Cancelada')], default='A Pagar', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor (R$)'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(upload_to=gestao.models.get_upload_path, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='caso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_caso', to='gestao.caso', verbose_name='Caso Associado (Opcional)'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_cliente', to='gestao.cliente', verbose_name='Cliente Associado (Opcional)'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_upload',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Upload'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nome_original_arquivo',
            field=models.CharField(max_length=255, verbose_name='Nome Original do Arquivo'),
        ),
        migrations.AlterField(
            model_name='eventoagenda',
            name='caso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_caso', to='gestao.caso', verbose_name='Caso Associado (Opcional)'),
        ),
        migrations.AlterField(
            model_name='eventoagenda',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='Concluído?'),
        ),
        migrations.AlterField(
            model_name='eventoagenda',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='eventoagenda',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='eventoagenda',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Fim'),
        ),
        migrations.AlterField(
            model_name='eventoagenda',
            name='data_inicio',
            field=models.DateTimeField(verbose_name='Data e Hora de Início'),
        ),
        migrations.AlterField(
            model_name='eventoagenda',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada'),
        ),
        migrations.AlterField(
            model_name='eventoagenda',
            name='local',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local (se aplicável)'),
        ),
        migrations.AlterField(
            model_name='eventoagenda',
            name='tipo_evento',
            field=models.CharField(choices=[('Prazo', 'Prazo Processual'), ('Audiência', 'Audiência'), ('Reunião', 'Reunião'), ('Lembrete', 'Lembrete'), ('Outro', 'Outro Compromisso')], max_length=50, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='eventoagenda',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título do Evento/Prazo'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos_caso', to='gestao.caso', verbose_name='Caso Associado'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='categoria',
            field=models.CharField(choices=[('Honorários Iniciais', 'Honorários Iniciais'), ('Honorários Mensais', 'Honorários Mensais'), ('Honorários de Êxito', 'Honorários de Êxito'), ('Custas Processuais', 'Custas Processuais (Reembolso)'), ('Acordo', 'Acordo'), ('Outros', 'Outros')], max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos_cliente', to='gestao.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Recebimento'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='data_vencimento',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Vencido', 'Vencido'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor (R$)'),
        ),
    ]
